version: '3.9'

services:


  cookiefest_api:
    container_name: cookiefest_api
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    command: ["poetry", "run", "uvicorn", "start:api", "--host", "0.0.0.0", "--port", "8000"]
    env_file:
      - .env
    ports:
      - ${API_BASE_PORT}:8000
    