"""empty message

Revision ID: 40542f08e436
Revises: c13debdf16ce
Create Date: 2024-11-30 22:20:49.282367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40542f08e436'
down_revision: Union[str, None] = 'c13debdf16ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_merchants',
    sa.Column('productMerchantsId', sa.Integer(), nullable=False),
    sa.Column('productId', sa.BigInteger(), nullable=False),
    sa.Column('merchantId', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['merchantId'], ['merchants.merchantId'], ),
    sa.ForeignKeyConstraint(['productId'], ['items.productId'], ),
    sa.PrimaryKeyConstraint('productMerchantsId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_merchants')
    # ### end Alembic commands ###
