"""empty message

Revision ID: 49a708a9ac1b
Revises: 40542f08e436
Create Date: 2024-11-30 22:23:24.558614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49a708a9ac1b'
down_revision: Union[str, None] = '40542f08e436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_tickets',
    sa.Column('marketTicketId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('report', sa.String(), nullable=False),
    sa.Column('created', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('marketTicketId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_tickets')
    # ### end Alembic commands ###
