"""empty message

Revision ID: 5ac29ce5453f
Revises: e301ceb6485f
Create Date: 2024-11-30 21:59:15.351442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ac29ce5453f'
down_revision: Union[str, None] = 'e301ceb6485f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('productCategoryId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'items', 'product_categories', ['productCategoryId'], ['productCategoryId'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_column('items', 'productCategoryId')
    # ### end Alembic commands ###
