"""empty message

Revision ID: bde17d1bffc9
Revises: a19a615b01a3
Create Date: 2024-11-30 15:22:31.017495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bde17d1bffc9'
down_revision: Union[str, None] = 'a19a615b01a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('phoneNumber', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'phoneNumber')
    # ### end Alembic commands ###
