"""empty message

Revision ID: e0742db119a2
Revises: 
Create Date: 2024-11-30 21:46:46.638003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0742db119a2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('merchantId', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('billingAddress', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('merchantId')
    )
    op.create_table('users',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('registeredAt', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('userId')
    )
    op.create_table('items',
    sa.Column('productId', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('articul', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('salePrice', sa.Integer(), nullable=True),
    sa.Column('sale', sa.Integer(), nullable=True),
    sa.Column('merchantId', sa.BigInteger(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('reviews', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['merchantId'], ['merchants.merchantId'], ),
    sa.PrimaryKeyConstraint('productId')
    )
    op.create_table('user_profile',
    sa.Column('userProfileID', sa.Integer(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('patronymic', sa.String(), nullable=False),
    sa.Column('phoneNumber', sa.String(length=20), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('userProfileID')
    )
    op.create_table('favorites',
    sa.Column('favoriteId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('productId', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['productId'], ['items.productId'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('favoriteId')
    )
    op.create_table('orders',
    sa.Column('orderId', sa.Integer(), nullable=False),
    sa.Column('productId', sa.BigInteger(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('orderedAt', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['productId'], ['items.productId'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('orderId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('favorites')
    op.drop_table('user_profile')
    op.drop_table('items')
    op.drop_table('users')
    op.drop_table('merchants')
    # ### end Alembic commands ###
